ALTER TABLE HabitLog DROP CONSTRAINT FKHabitLog356749;
ALTER TABLE RoutineHabit DROP CONSTRAINT FKRoutineHab690691;
ALTER TABLE RoutineHabit DROP CONSTRAINT FKRoutineHab214204;
DROP TABLE IF EXISTS Habit CASCADE;
DROP TABLE IF EXISTS HabitLog CASCADE;
DROP TABLE IF EXISTS HabitStatus CASCADE;
DROP TABLE IF EXISTS Routine CASCADE;
DROP TABLE IF EXISTS RoutineHabit CASCADE;
