# Database configuration (PostgreSQL)
quarkus.datasource.db-kind  = postgresql
quarkus.datasource.username = ${DB_USER}
quarkus.datasource.password = ${DB_PASS}
quarkus.datasource.jdbc.url = jdbc:postgresql://${DB_HOST:${QUARKUS_DB_HOST:localhost}}:${DB_PORT:${QUARKUS_DB_PORT:5432}}/${DB_NAME}

quarkus.hibernate-orm.schema-management.strategy = drop-and-create